FROM nvidia/cuda:11.7.1-devel-ubuntu22.04
#
RUN apt-get update && apt-get install -y --no-install-recommends     python3.5     python3-pip     wget    &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

COPY . .